interface Props {}

export const metadata = {
  title: 'About Page',
  description: 'Generated by Next.js',
};
const Head = ({}: Props) => {
  return (
    <>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};
export default Head;
